<?php
/**
 * <DZCP-Extended Edition>
 * @package: DZCP-Extended Edition
 * @author: DZCP Developer Team || Hammermaps.de Developer Team
 * @link: http://www.dzcp.de || http://www.hammermaps.de
 */

function emlv($id)
{
    switch ($id)
    {
        case 'eml_reg_subj':         return 'Deine Registrierung'; break;
        case 'eml_pwd_subj':         return 'Deine Zugangsdaten'; break;
        case 'eml_nletter_subj':     return 'Newsletter'; break;
        case 'eml_reg':              return '<p>Du hast dich erfolgreich auf unserer Seite registriert!</p>\r\n<table border="0" cellspacing="2" cellpadding="2" style="width: 400px;">\r\n<tbody>\r\n<tr>\r\n<td height="30" colspan="2">Deine Logindaten lauten:</td>\r\n</tr>\r\n<tr>\r\n<td colspan="2"><hr /></td>\r\n</tr>\r\n<tr>\r\n<td width="120">Login-Name:</td>\r\n<td>[user]</td>\r\n</tr>\r\n<tr>\r\n<td>Passwort:</td>\r\n<td>[pwd]</td>\r\n</tr>\r\n<tr>\r\n<td colspan="2"><hr /></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<p>[ Diese Email wurde automatisch generiert, bitte nicht antworten ]</p>'; break;
        case 'eml_pwd':              return '<p>Ein neues Passwort wurde f&uuml;r deinen Account generiert!</p>\r\n<table border="0" cellspacing="2" cellpadding="2" style="width: 400px;">\r\n<tbody>\r\n<tr>\r\n<td height="30" colspan="2">Deine Logindaten lauten:</td>\r\n</tr>\r\n<tr>\r\n<td colspan="2"><hr /></td>\r\n</tr>\r\n<tr>\r\n<td width="120">Login-Name:</td>\r\n<td>[user]</td>\r\n</tr>\r\n<tr>\r\n<td>Passwort:</td>\r\n<td>[pwd]</td>\r\n</tr>\r\n<tr>\r\n<td colspan="2"><hr /></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<p>[ Diese Email wurde automatisch generiert, bitte nicht antworten ]</p>'; break;
        case 'eml_nletter':          return '<p>[text]<br /><br />[ Diese Email wurde automatisch generiert, bitte nicht antworten ]</p>'; break;
        case 'eml_fabo_npost_subj':  return 'Neuer Beitrag auf abonniertes Thema im [titel]'; break;
        case 'eml_fabo_tedit_subj':  return 'Thread auf abonniertes Thema im [titel] wurde bearbeitet'; break;
        case 'eml_fabo_pedit_subj':  return 'Beitrag auf abonniertes Thema im [titel] wurde bearbeitet'; break;
        case 'eml_pn_subj':          return 'Neue PN auf [domain]'; break;
        case 'eml_fabo_npost':       return '<p>Hallo [nick],<br /><br /> [postuser] hat auf das Thema: [topic] auf der Website: "[titel]" geantwortet.<br /><br /> Den neuen Beitrag erreichst Du ber folgenden Link:<br /> <a href="http://[domain]/?index=forum&amp;action=showthread&amp;id=[id]&amp;page=[page]#p[entrys]">http://[domain]/?index=forum&amp;action=showthread&amp;id=[id]&amp;page=[page]#p[entrys]</a></p>\r\n<table border="0" cellspacing="2" cellpadding="2" style="width: 400px;">\r\n<tbody>\r\n<tr>\r\n<td height="30">[postuser] hat folgenden Text geschrieben:</td>\r\n</tr>\r\n<tr>\r\n<td><hr /></td>\r\n</tr>\r\n<tr>\r\n<td>[text]</td>\r\n</tr>\r\n<tr>\r\n<td><hr /></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<p>Mit freundlichen Grüßen,<br /><br />Dein [clan]</p>\r\n<p>[ Diese Email wurde automatisch generiert, bitte nicht antworten ]</p>'; break;
        case 'eml_fabo_tedit':       return '<p>Hallo [nick],<br /> <br /> Der Thread mit dem Titel: [topic] auf der Website: "[titel]" wurde soeben von [postuser] bearbeitet.<br /> Den bearbeitete Beitrag erreichst Du ber folgenden Link:<br /> <a href="http://[domain]/?index=forum&amp;action=showthread&amp;id=[id]">http://[domain]/?index=forum&amp;action=showthread&amp;id=[id]</a></p>\r\n<table border="0" cellspacing="2" cellpadding="2" style="width: 400px;">\r\n<tbody>\r\n<tr>\r\n<td height="30">[postuser] hat folgenden neuen Text geschrieben:</td>\r\n</tr>\r\n<tr>\r\n<td><hr /></td>\r\n</tr>\r\n<tr>\r\n<td>[text]</td>\r\n</tr>\r\n<tr>\r\n<td><hr /></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<p>Mit freundlichen Grüßen,<br /><br />Dein [clan]</p>\r\n<p>[ Diese Email wurde automatisch generiert, bitte nicht antworten ]</p>'; break;
        case 'eml_fabo_pedit':       return '<p>Hallo [nick],<br /><br /> Ein Beitrag im Thread mit dem Titel: [topic] auf der Website: "[titel]" wurde soeben von [postuser] bearbeitet.<br /> <br /> Den bearbeitete Beitrag erreichst Du ber folgenden Link:<br /> <a href="http://[domain]/?index=forum&amp;action=showthread&amp;id=[id]&amp;page=[page]#p[entrys]">http://[domain]/?index=forum&amp;action=showthread&amp;id=[id]&amp;page=[page]#p[entrys]</a></p>\r\n<table border="0" cellspacing="2" cellpadding="2" style="width: 400px;">\r\n<tbody>\r\n<tr>\r\n<td height="30">[postuser] hat folgenden neuen Text geschrieben:</td>\r\n</tr>\r\n<tr>\r\n<td><hr /></td>\r\n</tr>\r\n<tr>\r\n<td>[text]</td>\r\n</tr>\r\n<tr>\r\n<td><hr /></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<p>Mit freundlichen Grüßen,<br /><br />Dein [clan]</p>\r\n<p>[ Diese Email wurde automatisch generiert, bitte nicht antworten ]</p>'; break;
        case 'eml_pn':               return '<p>Hallo [nick],<br /><br /> Du hast eine neue Nachricht in deinem Postfach.</p>\r\n<table border="0" cellspacing="2" cellpadding="2" style="width: 400px;">\r\n<tbody>\r\n<tr>\r\n<td height="30">Titel: [titel]</td>\r\n</tr>\r\n<tr>\r\n<td><hr /></td>\r\n</tr>\r\n<tr>\r\n<td><a href="http://[domain]/user/index.php?action=msg">Zum Nachrichten-Center</a></td>\r\n</tr>\r\n<tr>\r\n<td><hr /></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<p>Mit freundlichen Grüßen,<br /><br />Dein [clan]</p>\r\n<p>[ Diese Email wurde automatisch generiert, bitte nicht antworten ]</p>'; break;
        case 'eml_akl_register_subj':return 'Dein Aktivierungslink'; break;
        case 'eml_akl_register':     return '<p>Hallo [nick],<br /> Dein Account muss noch aktiviert werden, danach kannst du dich anmelden.</p>\r\n<table border="0" cellspacing="2" cellpadding="2" style="width: 600px;">\r\n<tbody>\r\n<tr>\r\n<td height="30" colspan="2">Deine Aktivierung:</td>\r\n</tr>\r\n<tr>\r\n<td colspan="2"><hr /></td>\r\n</tr>\r\n<tr>\r\n<td width="120">Aktivierungslink:</td>\r\n<td>[link]</td>\r\n</tr>\r\n<tr>\r\n<td>Aktivierungscode:</td>\r\n<td>[guid]</td>\r\n</tr>\r\n<tr>\r\n<td colspan="2"><hr /></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<p>Falls der Link nicht funktioniert, kannst du den Aktivierungscode auch auf "[link_page]" eingeben.</p>\r\n<p>[ Diese Email wurde automatisch generiert, bitte nicht antworten ]</p>'; break;
    }
}